source 'https://rubygems.org'
git_source(:github) {|repo| "https://github.com/#{repo}.git"}

ruby '2.5.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.0'
# Use mysql as the database for Active Record
gem 'mysql2'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
gem 'rubocop-rspec'
# goto /version to see full version
gem  'git-version'

#https://github.com/zdennis/activerecord-import
gem 'activerecord-import'

#https://voormedia.github.io/rails-erd/install.html
gem "rails-erd"

#https://github.com/activerecord-hackery/ransack
gem 'ransack'

#https://github.com/activeadmin/activeadmin
#gem 'activeadmin'


gem "jquery"
gem 'jquery-rails'

#https://github.com/rweng/jquery-datatables-rails
gem 'jquery-datatables-rails', '~> 3.4.0'

#https://github.com/mkhairi/jquery-datatables
gem 'jquery-datatables' , '1.10.19.1'
 
#gem 'ajax-datatables-rails'

#http://ajahongir.github.io/ajax-datatables-rails/
gem 'ajax-datatables-rails'
gem 'rails_script'
gem 'js-routes'
gem 'responders' # if you are using rails 4.2+



gem 'sprockets-rails', '~>2.3.2'
#https://github.com/twbs/bootstrap-rubygem
gem 'bootstrap', '~> 4.1.3'

#https://github.com/mirego/gaffe
gem 'gaffe'


#helps with foreign keys
#https://github.com/jenseng/immigrant
gem 'immigrant'



#https://github.com/amerine/acts_as_tree
gem 'acts_as_tree'

gem 'nifty-generators'
 
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'mini_racer', platforms: :ruby
gem "font-awesome-rails"
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'

#https://github.com/ruby-json-schema/json-schema
gem 'json-schema'

#https://www.rubydoc.info/gems/render_async/1.2.0
gem 'render_async'


#https://github.com/fnando/paginate
#gem 'paginate', '~> 4.0.1'
#https://rubyinrails.com/2014/03/27/pagination-in-rails-using-will_paginate-gem/
#https://github.com/mislav/will_paginate

gem 'will_paginate', '~> 3.1.1'


# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

#adds simple nav
gem "simple-navigation"

gem 'superfish-rails'
gem 'seed_dump'
gem 'nokogiri'
gem 'awesome_print'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  
  #https://github.com/rspec/rspec-rails
  gem 'rspec-rails'
 end

group :test do
  #For fake data in tests
  #https://github.com/stympy/faker
  gem 'faker' 
  
  #https://github.com/DatabaseCleaner/database_cleaner
  gem 'database_cleaner'
  
  # https://github.com/thoughtbot/shoulda-matchers
  gem 'shoulda-matchers'
  
  #https://github.com/thoughtbot/factory_bot_rails
  gem 'factory_bot_rails', '~> 4.0'
  
end
 
group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  
  #https://joanswork.com/rubocop-rails-getting-started/
  #https://github.com/rubocop-hq/rubocop
  gem 'rubocop', require: false
  #https://github.com/causes/haml-lint
  gem 'haml-lint', require: false
end



# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
